package com.santo.vms.utilities.enums;

public enum EntityStatus {
    NONE,
    DRAFT,
    ACTIVE,
    DISABLED,
    PENDING,
    PENDING_APPROVAL,
    PENDING_VERIFICATION,
    PENDING_ADJUSTMENT,
    DISAPPROVED,
    INACTIVE,
    PROCESSING_IN_PROGRESS,
    PROCESSED,
    SUCCESSFUL,
    FAILED,
    PENDING_EDIT_APPROVAL,
    PENDING_REVISE_APPROVAL,
    DELETED,
    REDEEMED,
    BLOCKED,
    TEST_PENDING,
    MATURED,
    OUTSTANDING,
    PAYMENT_INITIATED,
    PENDING_DISPATCH,
    PENDING_CANCELLATION_APPROVAL
}
